config.yaml, content/studies/_index.md, content/studies/article/_index.md, content/studies/case-study/_index.md, content/tags/_index.md, content/tags/community/_index.md, content/tags/ospo/_index.md, layouts/index.html, layouts/resource/single.html
Issue solved:
- https://github.com/ospoplusplus/ospoplusplus/issues/12
=> Resources page

content/about/contact.md
Issue solve:
- https://github.com/ospoplusplus/ospoplusplus/issues/11
Hi @clcoffey ,
I couldn't handle the last request with html code which is "**_Other (can we add a text field when this is selected?)
Message_**"
Instead I configured the dropdown section with the options and user can input value as well. If that works for you, great! Otherwise, I need to find a solution with Javascript logic. This feature is not feasible with HTML at the time.
=> Create contact form

assets/scss/_common.scss, layouts/partials/page-header.html
Issues solved:
- https://github.com/ospoplusplus/ospoplusplus/issues/14
- https://github.com/ospoplusplus/ospoplusplus/issues/13
=> Modify styling

content/events/cc-2023-01-26.md
issue solved: https://github.com/ospoplusplus/ospoplusplus/issues/56
=> Edit the event link

content/events/cc-2023-01-19.md
- https://github.com/ospoplusplus/ospoplusplus/issues/62
=> Add Youtube link and active watch recording button

layouts/partials/header.html
- https://github.com/ospoplusplus/ospoplusplus/issues/63
=> Change the banner message

content/about/codeofconduct.md, layouts/events/list.html
Issues completes:
- https://github.com/ospoplusplus/ospoplusplus/issues/68
- https://github.com/ospoplusplus/ospoplusplus/issues/69
- https://github.com/ospoplusplus/ospoplusplus/issues/64
=> Add new text to Code of Conduct webpage and update Future Events section

content/events/c-2023-03-24.md
- https://github.com/ospoplusplus/ospoplusplus/issues/76
=> Change the event description

layouts/partials/header.html
Issues completed:
- https://github.com/ospoplusplus/ospoplusplus/issues/78
- https://github.com/ospoplusplus/ospoplusplus/issues/79
=> Update banner message

content/events/cc-2023-02-23.md
- https://github.com/ospoplusplus/ospoplusplus/issues/81
=> Add youtube link for the event

content/events/cc-2023-01-26.md
- https://github.com/ospoplusplus/ospoplusplus/issues/83
=> Update the youtube link for the event

content/resource/University-of-Vermont-VERSO.md
The issue applied: https://github.com/ospoplusplus/ospoplusplus/issues/88#issuecomment-1468646031
=> Fix typo in the resource

content/resource/OPEN-RIT.md
- https://github.com/ospoplusplus/ospoplusplus/issues/94
=> Fix typos in the resource

content/resource/Open-Source-with-SLU.md
- https://github.com/ospoplusplus/ospoplusplus/issues/96
=> Replace the link

content/resource/Carnegie-Mellon-University-OSPO.md, content/resource/Guide-To-Set-Up-A-University-Open-Source-Programs-Office.md, layouts/resource/list.html
Issues applied:
- https://github.com/ospoplusplus/ospoplusplus/issues/110
=> Remove summary of resources and fix typos

layouts/partials/header.html
Issues applied:
- https://github.com/ospoplusplus/ospoplusplus/issues/116
- https://github.com/ospoplusplus/ospoplusplus/issues/117
=> Update the banner

content/events/cc-2023-03-30.md, layouts/partials/header.html
Issues applied:
- https://github.com/ospoplusplus/ospoplusplus/issues/121
- https://github.com/ospoplusplus/ospoplusplus/issues/122
=> Add the youtube link to event and change the banner

content/events/c-2023-03-24.md
- https://github.com/ospoplusplus/ospoplusplus/issues/125
=> Add the youtube link to the event

content/events/wp-2023-06-21.md
New pull request with link to OFE webpage
=> Create Event description for June UN event OSPOs for Good

content/events/dg-2023-06-16.md
- https://github.com/ospoplusplus/ospoplusplus/issues/155
=> Update the event title

content/resource/Commercial-Open-Source-Software.md, content/resource/Open-Science-Technology-Transfer-and-Innovation.md
Issue applied:
- https://github.com/ospoplusplus/ospoplusplus/issues/168
=> Fix typos in the articles

content/resource/Open-Source-Policy-Trends-in-Europe.md, layouts/resource/single.html
https://github.com/ospoplusplus/ospoplusplus/issues/171
=> Fix typos in the article

content/resource/Guide-To-Set-Up-A-University-Open-Source-Programs-Office.md
Issue applied: https://github.com/ospoplusplus/ospoplusplus/issues/179
=> Add the license text to the guide page to

content/about/_index.md
Small change in the about page text
=> Delete about/organizing team and Jacob name of description
